Lab2CRUD/Day2/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('students/',include('students.urls')),
    path('stuff/',include('stuff.urls'))
]

Lab2CRUD/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

Lab2CRUD/students/urls.py
from django.urls import path

from .views import *


app_name = 'student'

urlpatterns = [
    path('insert', addstudent, name='addstudentname'),
    path('',list, name='liststudentname'),
    path('delete/<int:id>',deleteview,name='studentdelete'),
    path('update/<int:id>',editview,name='studentedit'),
]

Lab2CRUD/stuff/urls.py
from django.urls import path

from .views import *
app_name = 'stuff'

urlpatterns = [
    path('', list, name='listsupervisorname'),
    path('insert/', insert, name='insert'),
    path('delete/<int:id>',deleteview,name='superdelete'),
    path('update/<int:id>',editview,name='superedit')
]

Lab2CRUD/home/models.py
from django.db import models

# Create your models here.

Lab2CRUD/students/models.py
from django.db import models
from stuff.models import *

# Create your models here.

class Student(models.Model):
    id = models.AutoField(primary_key=True, db_column='ID')
    name = models.CharField(max_length=50)
    track = models.CharField(max_length=100)
    supervisor =models.ForeignKey(to='stuff.Stuff',on_delete=models.CASCADE)

Lab2CRUD/stuff/models.py
from django.db import models

# Create your models here.
class Stuff(models.Model):
    id=models.AutoField(primary_key=True, db_column='ID')
    name=models.CharField(max_length=50)

Lab2CRUD/Day2/views.py
from django.shortcuts import render

Lab2CRUD/home/views.py
from django.shortcuts import render,redirect
from .models import *
# Create your views here.

def home(request):
    return render(request, 'home.html')


    

Lab2CRUD/students/views.py
# It Works
# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
                      
# def deleteview(req,id):
#     Student.objects.filter(id=id).delete()
#     context={}
#     context['students']=Student.objects.all()
#     return render(req, 'student/list.html', context)

def deleteview(req, id):
    student = Student.objects.get(id=id)
    student.delete()
    # context={}
    # context['students']=Student.objects.all()
    return redirect('student:liststudentname')
    # return render(req, 'student/list.html', context)

def editview(req, id):
    if req.method == 'GET':
        student = Student.objects.get(id=id)
        supervisors = Stuff.objects.all()
        context = {
            'student': student,
            'stuff': supervisors,
        }
        return render(req, 'student/edit.html', context)
    else:
        student = Student.objects.get(id=id)
        student.name = req.POST['studentname']
        student.track = req.POST['trackname']
        student.supervisor_id = req.POST['stuffid']
        student.save()
        return redirect('/students/')

def list(req):
    context={}
    context['students']=Student.objects.all()
    return render(req, 'student/list.html', context)

def addstudent(req):
    if(req.method=="GET"):  
       supervisors=Stuff.objects.all()  
       return render(req,'student/add.html',{'stuff':supervisors})
    else:
        Student.objects.create(
            name=req.POST['studentname'],
            track = req.POST['trackname'],
            supervisor=Stuff.objects.get(id=req.POST['stuffid'])
        )
        return redirect('/students/')

    

Lab2CRUD/stuff/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
from .models import *

def list(req):
    supervisors = Stuff.objects.all()
    return render(req, 'stuff/list.html', {'stuffs': supervisors})

def insert(req):
    if req.method == "GET":
        return render(req, 'stuff/add.html')
    else:
        Stuff.objects.create(name=req.POST['stuffname'])
        return redirect('/stuff/')

def deleteview(req, id):
    supervisor = Stuff.objects.get(id=id)
    supervisor.delete()
    return redirect('stuff:listsupervisorname')

def editview(req, id):
    supervisor = Stuff.objects.get(id=id)
    if req.method == "GET":
        return render(req, 'stuff/edit.html', {'supervisor': supervisor})
    else:
        supervisor.name = req.POST['stuffname']
        supervisor.save()
        return redirect('/stuff/')

Lab2CRUD/home/templates/home.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title>
		{%block title%}
		parent page
		{%endblock%}
	</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<style>
		.navbar-brand {
			color: white;
			font-weight: bold;
			font-size: 24px;
		}
		.navbar-collapse {
			justify-content: center;
		}
		.navbar-nav .nav-item .nav-link {
			color: white;
			font-size: 18px;
			margin: 0 10px;
		}
		.navbar-nav .nav-item .nav-link:hover {
			color: #ffc107;
		}
		.navbar{
			background-color: black;
		}
	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg">
		<div class="container-fluid">
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav mx-auto">
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'student:liststudentname' %}">Students</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'student:addstudentname' %}">Add Student</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'stuff:listsupervisorname' %}">Stuff</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'stuff:insert' %}">Add Stuff</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Login</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Register</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container mt-5">
		
		{%block content%}
		<h1>Welcome to my website!</h1>
		parent page content
		{%endblock%}
	</div>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>	

Lab2CRUD/home/templates/student/add.html
{%extends 'home.html'%}

{% block content %}
  <div class="container">
    <h1>Add Student</h1>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="studentname">Student Name</label>
        <input type="hidden" name="id" value="{{student.id}}">
        <input type="text" class="form-control" id="studentname" name="studentname" required>
      </div>
      <div class="form-group">
        <label for="trackname">Track Name</label>
        <input type="text" class="form-control" id="trackname" name="trackname" required>
      </div>
      <div class="form-group">
        <label for="stuffid">Supervisor</label>
        <select name="stuffid" class="form-control">
          {% for supervisor in stuff %}
          <option value="{{supervisor.id}}">{{supervisor.name}}</option>
          {%endfor%}
        </select>                 
      </div>
      <br>
      <button type="submit" class="btn btn-primary">Add</button>
    </form>
  </div>
{% endblock %}

Lab2CRUD/home/templates/student/edit.html
{%extends 'home.html'%}


{% block content %}
  <div class="container">
    <h1>Edit Student</h1>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="studentname">Student Name</label>
        <input type="hidden" name="id" value="{{student.id}}">
        <input type="text" class="form-control" id="studentname" name="studentname" required value="{{student.name}}">
      </div>
      <div class="form-group">
        <label for="trackname">Track Name</label>
        <input type="text" class="form-control" id="trackname" name="trackname" required value="{{student.track}}">
      </div>
      <div class="form-group">
        <label for="stuffid">Supervisor</label>
        <select name="stuffid" class="form-control">
          {% for supervisor in stuff %}
          <option value="{{supervisor.id}}">{{supervisor.name}}</option>
          {%endfor%}
        </select>                 
      </div>
    
      <br>
      <button type="submit" class="btn btn-primary">Update</button>
    </form>
  </div>
{% endblock %}

Lab2CRUD/home/templates/student/list.html
{%extends 'home.html'%}

{% block content %}
<div class="container">
    <h1>Students</h1>
    <a href="" class="btn btn-primary">Add Student</a>
    <br><br>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Student Name</th>
                <th>Track Name</th>
                <th>Supervisor Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>{{ student.name }}</td>
                <td>{{ student.track }}</td>
                <td>{{ student.supervisor.name }}</td>
                <td>
                    <a href="{%url 'student:studentedit' student.id%}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{%url 'student:studentdelete' student.id%}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Lab2CRUD/home/templates/stuff/add.html
{%extends 'home.html'%}

{% block content %}
<div class="container">
  <h1>Add Supervisor</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="stuffname">Supervisor Name:</label>
      <input type="text" class="form-control" id="stuffname" name="stuffname" required>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Add</button>
  </form>
</div>
{% endblock %}

Lab2CRUD/home/templates/stuff/edit.html
{%extends 'home.html'%}

{% block content %}
  <div class="container">
    <h1>Edit Supervisor</h1>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="stuffname">Student Name</label>
        <input type="hidden" name="id" value="{{supervisor.id}}">
        <input type="text" class="form-control" id="stuffname" name="stuffname" required value="{{supervisor.name}}">
      </div>
      <button type="submit" class="btn btn-primary">Update</button>
    </form>
  </div>
{% endblock %}

Lab2CRUD/home/templates/stuff/list.html
{%extends 'home.html'%}

{% block content %}
<div class="container">
    <h1>Supervisors</h1>
    <br><br>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Supervisor Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for supervisor in stuffs %}
            <tr>
                <td>{{ supervisor.id }}</td>
                <td>{{ supervisor.name }}</td>
                <td>
                    <a href="{%url 'stuff:superedit' supervisor.id%}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{%url 'stuff:superdelete' supervisor.id%}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <a href="{%url 'stuff:insert' %}" class="btn btn-primary">Add New Supervisor</a>
</div>
{% endblock %}